language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19
env:
 matrix:
   - MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  — mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
