language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.4
sudo: false
script:
  - mix test
  - mix coveralls.travis
after_script:
  - mix credo
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch
